### PR TITLE
Use Unicode-emileys and replace text

### PR DESCRIPTION
**Pull request by exetico**
I can't get render with markdown or other solution to work, so this should:
- Render smileys as unicode
- Replace HTML-blocks
- Replace `:value:`

### CODE REVIEW

**Comment by exetico** [comment]
Hot-fix solution for #2 @angusmcleod  :-)

image

**Comment by exetico** [comment]
Another solution could be looking for <img, grapping the `src`, and creating everything in `h()`, if it's even possible? I'm not that good to the virtual-dom stuff, but i can't take another day with raw HTML in my sidebar :D

**Comment by angusmcleod** [comment]
@exetico This is fixed now. I've used the existing libs in Discourse to handle the html formatting and escaping: https://github.com/angusmcleod/layouts-topic-list/commit/f8911570ea873ce2228124820ad2a15f39b9a030

Sorry for the delay!

**Comment by exetico** [comment]
Hi @angusmcleod 

Thanks! Damn, i saw the rawhtml, but didn't think it was an option to use it like that. Thanks for the inputs! I really need to look by the options for the Discourse plugins. It's just hard to find it's way to all the options through the existing libs - which i doesn't know that great..  :-)

**Pull request closed without merging**
